In [1]:
import tensorflow as tf

In [2]:
r=tf.constant([1,2,3])

In [3]:
tf.print(r)

[1 2 3]


In [4]:
r2=tf.constant([[1,2,3],[4,5,6]],tf.float32)
tf.print(r2)

[[1 2 3]
 [4 5 6]]


In [5]:
r3=tf.constant("abcd",tf.string)
print(r3)

tf.Tensor(b'abcd', shape=(), dtype=string)


In [6]:
r2_boolean=tf.constant([True,False,True],tf.bool)
print(r2_boolean)

tf.Tensor([ True False  True], shape=(3,), dtype=bool)


In [7]:
z=tf.zeros((5,6))
z

<tf.Tensor: shape=(5, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [8]:
g=tf.ones((4,5))
g

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [9]:
val=tf.constant(3.123455,tf.float32)
val2=tf.cast(val,dtype=tf.int32)
tf.print(val2)

3


In [10]:
v=10 #rank 0
v=[1,2,3] #rank 1
v=[[5,6],[7,8]] #rank 2

In [11]:
import tensorflow.compat.v1 as tf

In [12]:
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [13]:
a=tf.placeholder(tf.float32) #assign value of tensor later

In [14]:
b=tf.cast(a*2,tf.float32)

In [15]:
with tf.Session() as sess: #session used to store value for a lonf period of time
    result=sess.run(b,feed_dict={a:3.0})

In [16]:
result

6.0

In [29]:
#functions and Session

In [27]:
n=tf.constant(64,dtype=tf.float32)
m=tf.sqrt(n)
with tf.Session() as sess:
    result=sess.run(m)
    print(result) #it will square root of 64

8.0


In [38]:
a=tf.constant(3,dtype=tf.int32)
b=tf.constant(4,dtype=tf.int32)
c=tf.add(a,b)
with tf.Session() as sess:
    result=sess.run(c)
    print(result) #it will add 3 and 4

7


In [30]:
#f(x,z)=xz+x^2+z+5

In [35]:
x=tf.constant([7],dtype=tf.int32)
z=tf.constant([6],dtype=tf.int32)
const=tf.constant([5],dtype=tf.int32)
f=tf.multiply(x,z)+tf.pow(x,2)+z+c
f

<tf.Tensor 'add_11:0' shape=(1,) dtype=int32>

In [36]:
with tf.Session() as sess:
    result=sess.run(f)
    print(result)

[104]
