In [ ]:
#A Vanilla LSTM is an LSTM model that has a single hidden layer of LSTM units, and an output layer used to make a prediction. We can define a Vanilla LSTM for univariate time series forecasting

In [82]:
sequence=[10,20,30,40,50,60,70,80,90]

In [83]:
'''X                 y
10,20,30             40
20,30,40             50'''

'X                 y\n10,20,30             40\n20,30,40             50'

In [84]:
import numpy as np
def split_sequence(sequence,n_steps):
    X,y=list(),list()
    for i in range(len(sequence)):
        #find the end of this pattern
        end_ix=i+n_steps
        if end_ix>len(sequence)-1:
            break
            
        #gather input and output parts of the pattern
        seq_x,seq_y=sequence[i:end_ix],sequence[end_ix]
        X.append(seq_x)
        y.append(seq_y)
    return np.array(X),np.array(y)    
    

In [85]:
n_steps=3

In [86]:
X,y=split_sequence(sequence,n_steps)

In [87]:
X

array([[10, 20, 30],
       [20, 30, 40],
       [30, 40, 50],
       [40, 50, 60],
       [50, 60, 70],
       [60, 70, 80]])

In [88]:
y

array([40, 50, 60, 70, 80, 90])

In [89]:
for i in range(len(X)):
    print(X[i],y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


In [90]:
#vanilla LSTM has only one layer

In [91]:
from keras.layers import Dense,LSTM
from keras.models import Sequential

In [92]:
n_features=1 #for univarient n_features always be 1

In [93]:
model=Sequential()
model.add(LSTM(50,activation='relu',input_shape=(n_steps,n_features)))
model.add(Dense(1))

In [94]:
model.compile(optimizer='adam',loss='mse')

In [95]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_3 (LSTM)                (None, 50)                10400     
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 51        
Total params: 10,451
Trainable params: 10,451
Non-trainable params: 0
_________________________________________________________________


In [96]:
X.shape

(6, 3)

In [97]:
#convert to 3D array
X=X.reshape((X.shape[0],X.shape[1],n_features))
X

array([[[10],
        [20],
        [30]],

       [[20],
        [30],
        [40]],

       [[30],
        [40],
        [50]],

       [[40],
        [50],
        [60]],

       [[50],
        [60],
        [70]],

       [[60],
        [70],
        [80]]])

In [98]:
model.fit(X,y,epochs=200)

Epoch 1/200
1/1 [==============================] - 1s 1s/step - loss: 4584.2803
Epoch 2/200
1/1 [==============================] - 0s 10ms/step - loss: 4551.8384
Epoch 3/200
1/1 [==============================] - 0s 7ms/step - loss: 4519.3667
Epoch 4/200
1/1 [==============================] - 0s 12ms/step - loss: 4486.8179
Epoch 5/200
1/1 [==============================] - 0s 14ms/step - loss: 4454.2817
Epoch 6/200
1/1 [==============================] - 0s 15ms/step - loss: 4421.7334
Epoch 7/200
1/1 [==============================] - 0s 17ms/step - loss: 4389.0781
Epoch 8/200
1/1 [==============================] - 0s 11ms/step - loss: 4356.1255
Epoch 9/200
1/1 [==============================] - 0s 19ms/step - loss: 4322.8262
Epoch 10/200
1/1 [==============================] - 0s 26ms/step - loss: 4289.1079
Epoch 11/200
1/1 [==============================] - 0s 13ms/step - loss: 4254.8521
Epoch 12/200
1/1 [==============================] - 0s 24ms/step - loss: 4219.9292
Epoch 13/200
1/1

In [99]:
#predicting next value in sequence
x_input=np.array([70,80,90])
x_input=x_input.reshape((1,n_steps,n_features))

In [100]:
yhat=model.predict(x_input)

In [101]:
yhat

array([[101.527695]], dtype=float32)