In [294]:
import pandas as pd

In [295]:
train=pd.read_csv("C:\\Users\\user\\Downloads\\train (2).csv")

In [296]:
train.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [297]:
#function to remove punctuatuions
import string
from string import punctuation
def remove_punc(text):
    for i in text:
        if i in punctuation:
            text=text.replace(i,"")
    return text     
    

In [298]:
train["text"]=train.text.map(lambda x:remove_punc(x))

In [299]:
train["text"]

0       Our Deeds are the Reason of this earthquake Ma...
1                   Forest fire near La Ronge Sask Canada
2       All residents asked to shelter in place are be...
3       13000 people receive wildfires evacuation orde...
4       Just got sent this photo from Ruby Alaska as s...
                              ...                        
7608    Two giant cranes holding a bridge collapse int...
7609    ariaahrary TheTawniest The out of control wild...
7610    M194 0104 UTC5km S of Volcano Hawaii httptcozD...
7611    Police investigating after an ebike collided w...
7612    The Latest More Homes Razed by Northern Califo...
Name: text, Length: 7613, dtype: object

In [300]:
#function to remove URLs:
import re
def remove_url(text):
    return re.sub(r"http\S+","",text) #\S means all letters until a space comes,+ means more than 1

In [301]:
train["text"]=train.text.map(lambda x:remove_url(x)) #map is used instead of a loop

In [302]:
#removing emojis
import emoji

In [303]:
emoji.UNICODE_EMOJI #ALl the emoji list

{'en': {'🥇': ':1st_place_medal:',
  '🥈': ':2nd_place_medal:',
  '🥉': ':3rd_place_medal:',
  '🆎': ':AB_button_(blood_type):',
  '🏧': ':ATM_sign:',
  '🅰️': ':A_button_(blood_type):',
  '🅰': ':A_button_(blood_type):',
  '🇦🇫': ':Afghanistan:',
  '🇦🇱': ':Albania:',
  '🇩🇿': ':Algeria:',
  '🇦🇸': ':American_Samoa:',
  '🇦🇩': ':Andorra:',
  '🇦🇴': ':Angola:',
  '🇦🇮': ':Anguilla:',
  '🇦🇶': ':Antarctica:',
  '🇦🇬': ':Antigua_&_Barbuda:',
  '♒': ':Aquarius:',
  '🇦🇷': ':Argentina:',
  '♈': ':Aries:',
  '🇦🇲': ':Armenia:',
  '🇦🇼': ':Aruba:',
  '🇦🇨': ':Ascension_Island:',
  '🇦🇺': ':Australia:',
  '🇦🇹': ':Austria:',
  '🇦🇿': ':Azerbaijan:',
  '🔙': ':BACK_arrow:',
  '🅱️': ':B_button_(blood_type):',
  '🅱': ':B_button_(blood_type):',
  '🇧🇸': ':Bahamas:',
  '🇧🇭': ':Bahrain:',
  '🇧🇩': ':Bangladesh:',
  '🇧🇧': ':Barbados:',
  '🇧🇾': ':Belarus:',
  '🇧🇪': ':Belgium:',
  '🇧🇿': ':Belize:',
  '🇧🇯': ':Benin:',
  '🇧🇲': ':Bermuda:',
  '🇧🇹': ':Bhutan:',
  '🇧🇴': ':Bolivia:',
  '🇧🇦': ':Bosnia_&_Herzegovina:',
  '🇧🇼': ':Botsw

In [304]:
def remove_emoji(text):
    allchars=[k for k in text]
    emoji_list=[c for c in allchars if c in emoji.UNICODE_EMOJI]
    clean_text=" ".join([j for j in text.split() if not any (i for i in emoji_list)])
    return clean_text
    #any return true if the item is there,else it will give false

In [305]:
train["text"]=train.text.map(lambda x:remove_emoji(x))
train["text"]

0       Our Deeds are the Reason of this earthquake Ma...
1                   Forest fire near La Ronge Sask Canada
2       All residents asked to shelter in place are be...
3       13000 people receive wildfires evacuation orde...
4       Just got sent this photo from Ruby Alaska as s...
                              ...                        
7608    Two giant cranes holding a bridge collapse int...
7609    ariaahrary TheTawniest The out of control wild...
7610                 M194 0104 UTC5km S of Volcano Hawaii
7611    Police investigating after an ebike collided w...
7612    The Latest More Homes Razed by Northern Califo...
Name: text, Length: 7613, dtype: object

In [306]:
#removing stopwords
from nltk.corpus import stopwords
stop=set(stopwords.words("english"))#set will create unique stopwords

In [307]:
def remove_stopwords(text):
    [i.lower() for i in text.split() if i.lower() not in stop]
    return "".join(text)

In [308]:
train["text"]=train.text.map(remove_stopwords)
train["text"]

0       Our Deeds are the Reason of this earthquake Ma...
1                   Forest fire near La Ronge Sask Canada
2       All residents asked to shelter in place are be...
3       13000 people receive wildfires evacuation orde...
4       Just got sent this photo from Ruby Alaska as s...
                              ...                        
7608    Two giant cranes holding a bridge collapse int...
7609    ariaahrary TheTawniest The out of control wild...
7610                 M194 0104 UTC5km S of Volcano Hawaii
7611    Police investigating after an ebike collided w...
7612    The Latest More Homes Razed by Northern Califo...
Name: text, Length: 7613, dtype: object

In [309]:
from collections import Counter

In [310]:
train["text"].values

array(['Our Deeds are the Reason of this earthquake May ALLAH Forgive us all',
       'Forest fire near La Ronge Sask Canada',
       'All residents asked to shelter in place are being notified by officers No other evacuation or shelter in place orders are expected',
       ..., 'M194 0104 UTC5km S of Volcano Hawaii',
       'Police investigating after an ebike collided with a car in Little Portugal Ebike rider suffered serious nonlife threatening injuries',
       'The Latest More Homes Razed by Northern California Wildfire ABC News'],
      dtype=object)

In [311]:
def counter_word(text):
    counter=Counter()
    for i in text.values:
        for word in i.split():
            counter[word]+=1
    return counter        
        

In [312]:
text=train.text

In [313]:
counter=counter_word(text)
counter

Counter({'Our': 26,
         'Deeds': 2,
         'are': 347,
         'the': 2595,
         'Reason': 5,
         'of': 1731,
         'this': 347,
         'earthquake': 26,
         'May': 16,
         'ALLAH': 1,
         'Forgive': 1,
         'us': 66,
         'all': 191,
         'Forest': 38,
         'fire': 174,
         'near': 50,
         'La': 11,
         'Ronge': 1,
         'Sask': 1,
         'Canada': 7,
         'All': 54,
         'residents': 5,
         'asked': 9,
         'to': 1815,
         'shelter': 5,
         'in': 1777,
         'place': 26,
         'being': 68,
         'notified': 1,
         'by': 472,
         'officers': 8,
         'No': 60,
         'other': 33,
         'evacuation': 35,
         'or': 181,
         'orders': 11,
         'expected': 14,
         '13000': 4,
         'people': 164,
         'receive': 2,
         'wildfires': 10,
         'California': 113,
         'Just': 49,
         'got': 104,
         'sent': 12,
        

In [314]:
len(counter)

22226

In [315]:
num_words=len(counter)

In [316]:
max_length=20 #number of words in a sequence

In [317]:
train.shape[0]

7613

In [ ]:
#split into training and testing datasets

In [318]:
train_size=int(train.shape[0]*0.8) #training size

In [319]:
train_sentences=train.text[:train_size] #training text
train_labels=train.target[:train_size] #training targets

In [320]:
test_sentences=train.text[train_size:]
test_labels=train.target[train_size:]

In [341]:
train_sentences

0       Our Deeds are the Reason of this earthquake Ma...
1                   Forest fire near La Ronge Sask Canada
2       All residents asked to shelter in place are be...
3       13000 people receive wildfires evacuation orde...
4       Just got sent this photo from Ruby Alaska as s...
                              ...                        
6085    Do you feel like you are sinking in low selfim...
6086    After a Few Years Afloat Pension Plans Start S...
6087    Do you feel like you are sinking in unhappines...
6088    With a sinking music video tv career Brooke Ho...
6089    supernovalester I feel so bad for them I can l...
Name: text, Length: 6090, dtype: object

In [321]:
test_sentences

6090    nowplaying Sinking Fast Now or Never on North ...
6091    that horrible sinking feeling when you‰Ûªve be...
6092    Nigga car sinking but he snapping it up for fo...
6093    abandonedpics You should delete this one its n...
6094    that horrible sinking feeling when you‰Ûªve be...
                              ...                        
7608    Two giant cranes holding a bridge collapse int...
7609    ariaahrary TheTawniest The out of control wild...
7610                 M194 0104 UTC5km S of Volcano Hawaii
7611    Police investigating after an ebike collided w...
7612    The Latest More Homes Razed by Northern Califo...
Name: text, Length: 1523, dtype: object

In [322]:
from keras.preprocessing.text import Tokenizer

In [323]:
tokenizer=Tokenizer(num_words=num_words)

In [324]:
tokenizer.fit_on_texts(train_sentences)

In [325]:
tokenizer.word_index

{'the': 1,
 'a': 2,
 'to': 3,
 'in': 4,
 'of': 5,
 'and': 6,
 'i': 7,
 'is': 8,
 'for': 9,
 'on': 10,
 'you': 11,
 'my': 12,
 'with': 13,
 'it': 14,
 'that': 15,
 'by': 16,
 'at': 17,
 'this': 18,
 'are': 19,
 'from': 20,
 'be': 21,
 'was': 22,
 'have': 23,
 'up': 24,
 'me': 25,
 'like': 26,
 'just': 27,
 'as': 28,
 'so': 29,
 'amp': 30,
 'but': 31,
 'not': 32,
 'fire': 33,
 'im': 34,
 'your': 35,
 'out': 36,
 'no': 37,
 'will': 38,
 'an': 39,
 'after': 40,
 'all': 41,
 'its': 42,
 'when': 43,
 'if': 44,
 'we': 45,
 'get': 46,
 'has': 47,
 'via': 48,
 'new': 49,
 'now': 50,
 'more': 51,
 'about': 52,
 'or': 53,
 'people': 54,
 'he': 55,
 'what': 56,
 'over': 57,
 'they': 58,
 'news': 59,
 'dont': 60,
 'emergency': 61,
 'do': 62,
 'how': 63,
 'one': 64,
 'been': 65,
 '2': 66,
 'us': 67,
 'into': 68,
 'there': 69,
 'were': 70,
 'can': 71,
 'video': 72,
 'disaster': 73,
 'burning': 74,
 'body': 75,
 'than': 76,
 'her': 77,
 'would': 78,
 'buildings': 79,
 'police': 80,
 'who': 81,
 'his':

In [326]:
train_sequences=tokenizer.texts_to_sequences(train_sentences)
train_sequences 

[[96, 3863, 19, 1, 804, 5, 18, 324, 108, 1396, 3864, 67, 41],
 [146, 33, 212, 680, 5801, 5802, 1397],
 [41,
  1564,
  1299,
  3,
  2001,
  4,
  597,
  19,
  111,
  5803,
  16,
  1565,
  37,
  429,
  196,
  53,
  2001,
  4,
  597,
  1089,
  19,
  1300],
 [2365, 54, 3865, 1183, 196, 1089, 4, 88],
 [27, 92, 1184, 18, 453, 20, 5804, 1753, 28, 1005, 20, 1183, 5805, 68, 2, 167],
 [2366,
  454,
  88,
  1301,
  654,
  714,
  4,
  750,
  5806,
  469,
  3,
  1185,
  470,
  33,
  5807,
  1183],
 [175, 73, 715, 388, 1090, 751, 197, 5, 1754, 4, 5808, 859, 2002, 1398],
 [34, 10, 209, 5, 1, 2367, 6, 7, 71, 103, 2, 33, 4, 1, 5809],
 [325, 39, 61, 196, 1006, 50, 4, 1, 530, 805, 1, 681],
 [34, 2368, 15, 1, 2369, 8, 267, 3, 96, 430],
 [624, 54, 492, 20, 1, 240, 389, 29, 509],
 [860,
  569,
  2370,
  8,
  221,
  2371,
  2937,
  625,
  2,
  716,
  7,
  276,
  4,
  569,
  2370,
  56,
  185,
  7,
  277,
  62,
  56,
  185,
  7,
  277,
  62,
  5810,
  197],
 [2938, 197, 2003, 5811, 2370, 1399, 53, 1566, 626, 3

In [327]:
train_sequences[0] #vectors given to first sentence

[96, 3863, 19, 1, 804, 5, 18, 324, 108, 1396, 3864, 67, 41]

In [328]:
#padding

In [329]:
from keras.preprocessing.sequence import pad_sequences
train_padded=pad_sequences(
       train_sequences,maxlen=max_length,padding="post",truncating="post"
)

In [330]:
train_padded[0]

array([  96, 3863,   19,    1,  804,    5,   18,  324,  108, 1396, 3864,
         67,   41,    0,    0,    0,    0,    0,    0,    0])

In [331]:
print(train.text[0])
print(train_sequences[0])
print(train_padded[0])

Our Deeds are the Reason of this earthquake May ALLAH Forgive us all
[96, 3863, 19, 1, 804, 5, 18, 324, 108, 1396, 3864, 67, 41]
[  96 3863   19    1  804    5   18  324  108 1396 3864   67   41    0
    0    0    0    0    0    0]


In [332]:
test_sequences=tokenizer.texts_to_sequences(test_sentences)
test_sequences 

[[759, 1370, 806, 50, 53, 204, 10, 629, 833, 972, 778, 17],
 [15,
  475,
  1370,
  931,
  43,
  65,
  17,
  154,
  10,
  35,
  500,
  9,
  2,
  257,
  6,
  11,
  42,
  65,
  10,
  18,
  542,
  99],
 [1418, 122, 1370, 31, 55, 14, 24, 9, 2176, 1281, 8873],
 [11, 178, 10963, 18, 64, 42, 32, 39, 8204, 1370, 4476, 1, 5, 1, 2720],
 [15,
  475,
  1370,
  931,
  43,
  65,
  17,
  154,
  10,
  35,
  500,
  9,
  2,
  257,
  6,
  11,
  42,
  65,
  10,
  18,
  542,
  99],
 [156, 1503, 10614, 1174, 1011, 35, 261, 1033, 2, 1370, 8301],
 [230, 4237],
 [15,
  475,
  1370,
  931,
  43,
  65,
  17,
  154,
  10,
  35,
  500,
  9,
  2,
  257,
  6,
  11,
  42,
  65,
  10,
  18,
  542,
  99],
 [44, 168, 752, 6, 1010, 53, 168, 1370, 26, 2, 3323, 3114],
 [7738, 3269, 1370, 4092, 1340, 3407, 619, 163, 865, 217, 481],
 [1797, 180, 3703, 359, 1, 1370, 401, 4, 1, 1386, 997, 56, 2, 1844],
 [45, 1141, 1, 5, 2, 1370, 1105],
 [1, 1370, 1105, 1761, 8, 10, 3686, 3323],
 [15,
  475,
  1370,
  931,
  43,
  65,
  17,
  15

In [333]:
test_padded=pad_sequences(
       test_sequences,maxlen=max_length,padding="post",truncating="post"
)

In [334]:
from keras.models import Sequential
from keras.layers import Embedding,LSTM,Dense,Dropout
model=Sequential()
model.add(Embedding(num_words,32,input_length=max_length))
model.add(LSTM(64)) #lstm remebers the words for a long time
model.add(Dropout(0.2))
model.add(Dense(1,activation='sigmoid'))

In [335]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [336]:
history=model.fit(train_padded,train_labels,epochs=20,validation_data=(test_padded,test_labels))

Epoch 1/20
191/191 [==============================] - 11s 43ms/step - loss: 0.5448 - accuracy: 0.7255 - val_loss: 0.4817 - val_accuracy: 0.7859
Epoch 2/20
191/191 [==============================] - 5s 24ms/step - loss: 0.3046 - accuracy: 0.8796 - val_loss: 0.5355 - val_accuracy: 0.7544
Epoch 3/20
191/191 [==============================] - 4s 23ms/step - loss: 0.1757 - accuracy: 0.9419 - val_loss: 0.6851 - val_accuracy: 0.7321
Epoch 4/20
191/191 [==============================] - 5s 26ms/step - loss: 0.1187 - accuracy: 0.9668 - val_loss: 0.7170 - val_accuracy: 0.7354
Epoch 5/20
191/191 [==============================] - 6s 31ms/step - loss: 0.0950 - accuracy: 0.9716 - val_loss: 0.7918 - val_accuracy: 0.7275
Epoch 6/20
191/191 [==============================] - 5s 28ms/step - loss: 0.0787 - accuracy: 0.9754 - val_loss: 0.9998 - val_accuracy: 0.7216
Epoch 7/20
191/191 [==============================] - 5s 26ms/step - loss: 0.0654 - accuracy: 0.9773 - val_loss: 0.9113 - val_accuracy: 0.728

In [337]:
y_pred=model.predict(test_padded)
y_pred

array([[7.3805437e-05],
       [5.7629049e-03],
       [1.3852814e-01],
       ...,
       [9.9779344e-01],
       [9.9947250e-01],
       [9.9975836e-01]], dtype=float32)

In [338]:
import numpy as np

In [339]:
y_pred=np.where(y_pred>0.5,1,0)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [1],
       [1],
       [1]])

In [340]:
y_pred=y_pred.flatten()
y_pred

array([0, 0, 0, ..., 1, 1, 1])