In [15]:
import numpy as np

In [16]:
rewards=np.array([
    [-1,-1,-1,-1,0,-1],
    [-1,-1,-1,0,-1,100],
    [-1,-1,-1,0,-1,-1],
    
    [-1,0,0,-1,0,-1],
    [0,-1,-1,0,-1,-1],
    [-1,0,-1,-1,-1,-1]
])


In [17]:
import pandas as pd
pd.DataFrame(rewards)

0  1  2  3  4    5
0 -1 -1 -1 -1  0   -1
1 -1 -1 -1  0 -1  100
2 -1 -1 -1  0 -1   -1
3 -1  0  0 -1  0   -1
4  0 -1 -1  0 -1   -1
5 -1  0 -1 -1 -1   -1

In [18]:
def initialize_q(m,n):
    return np.zeros((m,n))

In [19]:
q_matrix=initialize_q(6,6)

In [20]:
pd.DataFrame(q_matrix)

0    1    2    3    4    5
0  0.0  0.0  0.0  0.0  0.0  0.0
1  0.0  0.0  0.0  0.0  0.0  0.0
2  0.0  0.0  0.0  0.0  0.0  0.0
3  0.0  0.0  0.0  0.0  0.0  0.0
4  0.0  0.0  0.0  0.0  0.0  0.0
5  0.0  0.0  0.0  0.0  0.0  0.0

In [21]:
import random

In [22]:
def set_initial_state(rooms=6):
    return np.random.randint(0,rooms)

In [23]:
def get_action(current_state,reward_matrix):
    valid_actions=[]
    for action in enumerate(reward_matrix[current_state]):
        if action[1]!=-1:
            valid_actions+=[action[0]]
    return random.choice(valid_actions)        

In [24]:
#Q(State,action)=R(state,action)+Gamma*Max[Q(nextState,allActions_(nextstate))]
#take action based on previous state
def take_action(current_state,reward_matrix,gamma,verbose=False):
    action=get_action(current_state,reward_matrix)
    sa_reward=reward_matrix[current_state,action] #current state action reward
    ns_reward=max(q_matrix[action,]) #next state reward
    q_current_state=sa_reward+(gamma*ns_reward)
    q_matrix[current_state,action]=q_current_state
    new_state=action
    if verbose:
        print(q_matrix)
        print(f"Old State{current_state} | New State:{new_state}\n\n")
        if new_state==5:
              print("Agent has reached its goal")
    return new_state          

In [25]:
def initialize_episode(reward_matrix,initial_state,gamma,verbose=False):
    current_state=initial_state
    while True:
        current_state=take_action(current_state,reward_matrix,gamma,verbose)
        if current_state==5:
            break

In [26]:
def train_agent(iterations,reward_matrix,gamma,verbose=False):
    for episode in range(iterations):
        initial_state=set_initial_state()
        initialize_episode(reward_matrix,initial_state,gamma,verbose)
    return q_matrix

In [27]:
def normalize_matrix(q_matrix):
    normalized_q=q_matrix/max(q_matrix[q_matrix.nonzero()])*100
    return normalized_q.astype(int)

In [28]:
gamma=0.1
initial_state=set_initial_state()
initial_action=get_action(initial_state,rewards)
initialize_episode(rewards,initial_state,gamma,True)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Old State2 | New State:3


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
Old State3 | New State:1


[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]]
Old State1 | New State:5


Agent has reached its goal


In [29]:
gamma=0.1
initial_state=set_initial_state()
initial_action=get_action(initial_state,rewards)
q_table=train_agent(2000,rewards,gamma,False)

In [31]:
pd.DataFrame(normalize_matrix(q_table))

0   1  2  3  4    5
0  0   0  0  0  0    0
1  0   0  0  1  0  100
2  0   0  0  1  0    0
3  0  10  0  0  0    0
4  0   0  0  1  0    0
5  0  10  0  0  0    0

In [32]:
def deploy_agent(init_state,q_table):
    print("Start:",init_state)
    state=init_state
    steps=0
    while True:
        steps+=1
        action=np.argmax(q_table[state,:])
        print(action)
        state=action
        if action==5:
            print("Finished")
            return steps

In [33]:
start_room=1
steps=deploy_agent(start_room,q_table)
print("Number of rooms/actions",steps)

Start: 1
5
Finished
Number of rooms/actions 1
