In [1]:
#in reinforcement learning the agent is bound to learn by its own experience

In [2]:
#no need to preprogam agent #Bellman Equation is most important in RL used in Q -learning

In [3]:
#if the agent reaches the endpoint,the agent is rewarded

In [4]:
#Robots in a warehouse

In [6]:
#Define enviornment-state,action,reward
#shape enviornment(states)
enviornment_rows=11
enviornment_columns=11

In [9]:
#Q(s,a)=0 #a-action is up,left,right,down
import numpy as np
q_values=np.zeros((enviornment_rows,enviornment_columns,4)) #4 for 4 states-up,left,right,down

In [10]:
q_values #row -state, column-action

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
      

In [11]:
actions=['up','left','right','down']

In [12]:
#goal=green=100,black=-100=termination,rest path=-1=white

In [15]:
rewards=np.full((enviornment_rows,enviornment_columns),-100)
rewards #filling all matrix value with -100

array([[-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100]])

In [17]:
rewards[0,5]=100 #setting goal as 100,(i.e reward for packaging area)
rewards

array([[-100, -100, -100, -100, -100,  100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100],
       [-100, -100, -100, -100, -100, -100, -100, -100, -100, -100, -100]])

In [18]:
#define aisle locations(white squares) with dictionary

In [21]:
aisels={}
aisels[1]=[i for i in range(1,10)]
aisels[2]=[1,7,9]
aisels[3]=[i for i in range(1,8)]
aisels[3].append(9)

In [1]:
#not completed