In [6]:
from keras import backend as k

In [7]:
k.backend() #that means keras use tensorflow as backend

'tensorflow'

In [9]:
data=k.placeholder(shape=(2,3))
k.int_shape(data)

(2, 3)

In [12]:
a=k.placeholder(shape=(4,2))
b=k.placeholder(shape=(2,3))
c=k.dot(a,b)
c  #it will only give shape,because we are not giving array

<KerasTensor: shape=(4, 3) dtype=float32 (created by layer 'tf.linalg.matmul_1')>

In [14]:
res=k.ones(shape=(2,3)) #array of ones
res

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [16]:
k.eval(res)  #just to give the output

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [18]:
d=k.variable([[10,20,30],[30,40,50]])
result=k.transpose(d)
result

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[10., 30.],
       [20., 40.],
       [30., 50.]], dtype=float32)>

In [19]:
from keras.models import Sequential
from keras.layers import Activation,Dense
from keras import initializers
from keras import constraints

In [20]:
model=Sequential()

In [21]:
model.add(Dense(32,input_shape=(16,),kernel_initializer='he_uniform',kernel_regularizer=None,kernel_constraint='MaxNorm',activation='relu'))
#first dense layer #first layer only need shape,because output of first layer will be input of second layer

In [22]:
model.add(Dense(16,activation='relu')) #adding dense layer using unit

In [23]:
model.add(Dense(8))

In [24]:
shape=(4,2)

In [25]:
import numpy as np

In [27]:
input=np.zeros(shape)
input

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
my_init=initializers.Zeros() #you can use ones also
model=Sequential()
model.add(Dense(512,input_shape=(784,),kernel_initializer=my_init))
#it will generate zeros for all input data

In [30]:
my_init=initializers.Constant(value=5)  #constant
model=Sequential()
model.add(Dense(512,input_shape=(784,),kernel_initializer=my_init))

In [32]:
my_constraint=constraints.MaxNorm(max_value=2,axis=0)
#the first dimension of array should have value <=2
model=Sequential()
model.add(Dense(512,input_shape=(784,),kernel_initializer=my_init,kernel_constraint=my_constraint))